import sqlite3
import random
from datetime import datetime

DB_PATH = "db/stock.db"
OUTPUT_FILE = "stock_pool.py"

def generate_pool_file(industry, min_cap, max_cap, limit=300):

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    query = """
    SELECT symbol
    FROM stock_info
    WHERE industry LIKE ?
    AND market_cap BETWEEN ? AND ?
    """

    cursor.execute(query, (f"%{industry}%", min_cap, max_cap))
    rows = cursor.fetchall()
    conn.close()

    symbols = [r[0] for r in rows]

    if len(symbols) == 0:
        print("未找到符合条件股票")
        return

    if len(symbols) > limit:
        symbols = random.sample(symbols, limit)

    # ===== 写文件 =====
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by pool_generator\n")
        f.write(f"# Industry: {industry}\n")
        f.write(f"# MarketCap: {min_cap/1e8}-{max_cap/1e8} 亿\n")
        f.write(f"# Created: {datetime.now()}\n\n")
        f.write("STOCK_POOL = [\n")

        for s in symbols:
            f.write(f'    "{s}",\n')

        f.write("]\n")

    print(f"已生成 stock_pool.py，股票数量: {len(symbols)}")


if __name__ == "__main__":
    industry = input("请输入行业关键词: ")
    min_cap = float(input("最小市值(亿): ")) * 1e8
    max_cap = float(input("最大市值(亿): ")) * 1e8

    generate_pool_file(industry, min_cap, max_cap)